packages:
  - "apps"
  - "packages/*"
minimumReleaseAge: 0
allowBuilds:
  browser-tabs-lock: false
  bufferutil: false
  core-js: false
  esbuild: true
  msgpackr-extract: true
  sharp: true
  spawn-sync: true
  utf-8-validate: false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plus: 0.2.9
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
minimumReleaseAgeExclude:
  - vite-plus
  - "@voidzero-dev/*"
  - oxlint
  - "@oxlint/*"
  - oxlint-tsgolint
  - "@oxlint-tsgolint/*"
  - oxfmt
  - "@oxfmt/*"
  - vitest
  - "@vitest/*"
